### PR TITLE
Allow fields to be specified when creating the tracker

### PR DESCRIPTION
**Pull request by martinburchell**

### CODE REVIEW

**Comment by TkTech** [comment]
Should `googleanalytics_fields` be processed as a real python dict (`ast.literal_eval`) or a JSON dict (`json.loads`) instead of passed straight through? This makes it more direct to modify the value of the dict from Python.

**Comment by martinburchell** [comment]
Good point - I'll take a look

**Comment by martinburchell** [comment]
Anything I can do to help move this one along?

**Comment by camfindlay** [comment]
+1 @martinburchell seems this extension sits in some twilight zone between CKAN 1 and 2. Does your PR work for both versions or just 2.x +? (relates to #21 discussion) 👍

**Comment by martinburchell** [comment]
@camfindlay I haven't tested this with CKAN 1 so I don't know for sure, but my change is really just changing the JavaScript that is sent to GA. So I wouldn't expect it to have broken anything.

**Comment by smotornyuk** [comment]
I agree, can't find anything in this code, that differs from existing code, so it can't break anything. Does anyone against merging this PR?

**Pull request merged**
