### PR TITLE
Remove genshi reference

### PR DESCRIPTION
**Pull request by miguelbgouveia**
Removing the reference to the genshi module in order to use this extensions successfully in ckan > 2.6 versions. Maybe this PR should be merge to a new version of the extension since this changes could add problem to early versions of ckan.

This PR is for the #20 issue.

### CODE REVIEW

**Comment by camfindlay** [comment]
Perhaps the current 0.0.x version (should it be 0.1.0 under semantic versioning?) can be tagged branched. Development on the CKAN >= 2.6.x version could remain on master while development on the CKAN 1.x.x compatible version could be on a second branch (any improvements to 1.x version could be simply forward ported to the master branch or we later simply deprecate the 1.x compatible version).

**Comment by miguelbgouveia** [comment]
Yes @camfindlay I think that's in order to maintain the project for the more recente ckan versions.

**Comment by camfindlay** [comment]
:+1: @miguelbgouveia - who is/are the maintainer/s on this extension?

**Comment by miguelbgouveia** [comment]
I don't known who maintain this extension. By the graphs we can see that is not changed almost a year.

**Comment by camfindlay** [comment]
@sebbacon @rossjones @seanh @johnmartin @johnglover et al. are there any active maintainers on this extension presently? :) What would be the next step required to get peer review and merge of this PR? Thanks :+1:

**Comment by rossjones** [comment]
None of the people you've mentioned as far as I am aware. I don't know current status, or if there's a replacement, or what effect the PR would have.

Would suggest pinging https://lists.okfn.org/mailman/listinfo/ckan-dev to request help.

**Comment by camfindlay** [comment]
Thanks for the reply @rossjones much appreciated. I'll go maintainer wrangling 😄

**Comment by camfindlay** [comment]
@miguelbgouveia would this issue be present on other 2.x.x versions of CKAN? If we created branches for major version compatibility would it be as simple as a CKAN 1.x branch and master (for active CKAN 2.x.x development)? I'm crafting an email to the ckan-dev listserv to see if we could get some movement on this :+1:

**Comment by miguelbgouveia** [comment]
I don't @camfindlay, just test in version 2.6.

**Comment by smotornyuk** [comment]
Thanks for activity. Recently became a maintainer, so some progress in reviewing is expected  :smiling_imp:
@miguelbgouveia  I'll check this PR with older versions in a few days(at least, before Monday). 
As for different branches - this is definitely required step, so i'll do it as well asap

**Comment by miguelbgouveia** [comment]
Thanks @smotornyuk. I am glad that there is someone taking care of this issue.

**Comment by smotornyuk** [comment]
Didn't noticed anything incorrect - merged/
As for branches - i created `ckan-v1.x`. New pull requests, that should work with old CKAN will be backported. Everything other will just be merged into master. 
Once again, thanks for participating:)

**Pull request merged**
